alternate: Jimmy Portfolio

# Assets
statics: / #//cdn.jsdelivr.net/gh/amehime/shoka@latest/

open_graph:
  #twitter_id:
  #google_plus:
  #fb_admins:
  #fb_app_id:

menu:
  home: / || home
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  # friends: /friends/ || heart

# Social Links
# Usage: `Key: permalink || icon || color`
# Key is the link label showing to end users.
# Value before `||` delimiter is the target permalink,
# secend value is the name of Font icon.
social:
  github: https://github.com/soeviturek || github || "#191717"
  #google: https://plus.google.com/yourname || google
  # twitter: https://x.com/Lanaoi719 || twitter || "#00aff0"
  # zhihu: https://www.zhihu.com/people/rurismzk || zhihu || "#1e88e5"
  # music: https://music.163.com/#/user/home?id=12886823 || cloud-music || "#e60026"
  # weibo: https://weibo.com/amehime || weibo || "#ea716e"
  # about: https://about.me/amehime || address-card || "#3b5998"
  # email: mailto:yourname@mail.com || envelope || "#55acd5"
  #facebook: https://www.facebook.com/yourname || facebook
  #stackoverflow: https://stackoverflow.com/yourname || stack-overflow
  youtube: https://www.youtube.com/channel/UCnsWbGo6Zep4qptCoIvm1Wg || youtube || "#191717"
  # bilibili: https://space.bilibili.com/1474270 || bilibili || "#00aff0"
  #instagram: https://instagram.com/yourname || instagram
  #skype: skype:yourname?call|chat || skype
  #douban: https://www.douban.com/people/yourname/ || douban

fireworks:
  enable: true # 是否启用
  color: # 烟花颜色
    - "rgba(245,40,145,.8)"
    - "rgba(255,184,129,.8)"
    - "rgba(0,209,255,.9)"
    - "rgba(151,93,185,.9)"


font:
  enable: false
  # global:
  #   family: Times New Roman
  #   size: 1.2
  # posts:
  #   size: 1.2


widgets:
  random_posts: false # 显示随机文章
  recent_comments: false # 显示最近评论



footer:
  # Specify the date when the site was setup. If not defined, current year will be used.
  since: 2024
  count: true

post:
  count: true


# ---------------------------------------------------------------
# Third Party Plugins & Services Settings
# ---------------------------------------------------------------

# Comments
# Valine
# For more information: https://valine.js.org, https://github.com/xCss/Valine
# valine:
#   appId: XlKvS5KYV51KerAG2AePtpTY-MdYXbMMI
#   appKey: hKJb8QoV7RNJv8nnta6rLp0s
#   placeholder: ヽ(○´∀`)ﾉ♪ # Comment box placeholder
#   pageSize: 10 # Pagination size
#   lang: en
#   serverURLs:
#     - https://xlkvs5ky.api.lncldglobal.com
#     - https://xlkvs5ky.engine.lncldglobal.com
#     - https://xlkvs5ky.rtm.lncldglobal.com
#     - https://xlkvs5ky.push.lncldglobal.com
#     - https://app-router.com
#   tagMember:
#     master:
#       # - deea5a8d259d17182a53be1772e4c182
#       - ApcCWTs8gbXwDAXaZumXXCh5
#     friend:
#       - deea5a8d259d17182a53be1772e4c182

# # bgm
# audio:
#    - title: 列表1
#       list:
#         - https://music.163.com/#/playlist?id=2943811283
#         - https://music.163.com/#/playlist?id=2297706586
#    - title: 列表2
#       list:
#         - https://music.163.com/#/playlist?id=2031842656

# Dependencies: https://github.com/amehime/hexo-renderer-multi-markdown-it
pangu: true

# ---------------------------------------------------------------
# analytics & SEO Settings
# ---------------------------------------------------------------


# Disable Baidu transformation on mobile devices.
disable_baidu_transformation: true

# Automatically add external URL with Base64 encrypt & decrypt.
exturl: true
